name: v_chat_media_editor
description: v chat media editor package from v chat sdk this package is used to edit images and videos
version: 1.2.2
homepage: https://v-chat-sdk.github.io/vchat-v2-docs/docs/intro
issue_tracker: https://github.com/v-chat-sdk/v_chat_media_editor/issues
repository: https://github.com/v-chat-sdk/v_chat_media_editor
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_painter_v2: ^2.1.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  meta: ^1.16.0
  v_platform: ^2.1.4
#  fc_native_video_thumbnail: ^0.17.2
  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.4.0
  image_cropper: ^9.1.0
  phosphor_flutter: ^2.1.0
  file_picker: ^10.2.0
  chewie: ^1.12.1
  video_player: ^2.10.0
  cached_network_image: ^3.4.1
  blurhash: ^1.2.0
  pro_image_editor: ^10.5.4
  v_video_compressor: ^1.2.1
  video_trimmer: ^5.0.0
  s_translation:
    path: ../s_translation
  super_up_core:
    path: ../super_up_core

dependency_overrides:

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
