name: v_chat_call_service
description: A Flutter package for managing foreground services during phone calls
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_task: ^9.1.0
  permission_handler: ^12.0.1
  wakelock_plus: ^1.3.2
  s_translation:
    path: ../s_translation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
